image_width: 320
image_height: 240
camera_name: narrow_stereo/left
camera_matrix:
  rows: 3
  cols: 3
  data: [252.54949,   0.     , 167.91133,
           0.     , 253.57423, 121.33096,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.092358, -0.153791, -0.000022, 0.006828, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.99522267,  0.0028159 , -0.0975905 ,
         -0.00056169,  0.99973258,  0.02311845,
          0.0976295 , -0.02295319,  0.99495811]
projection_matrix:
  rows: 3
  cols: 4
  data: [279.66372,   0.     , 204.11855,   0.     ,
           0.     , 279.66372, 117.35908,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
