image_width: 320
image_height: 240
camera_name: narrow_stereo/right
camera_matrix:
  rows: 3
  cols: 3
  data: [250.43021,   0.     , 167.69753,
           0.     , 249.47665, 113.88565,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.091235, -0.100039, -0.000899, 0.013886, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.99670784,  0.00436445, -0.08095946,
         -0.00623202,  0.99971994, -0.02282971,
          0.08083715,  0.02325909,  0.9964559 ]
projection_matrix:
  rows: 3
  cols: 4
  data: [279.66372,   0.     , 204.11855, -23.14288,
           0.     , 279.66372, 117.35908,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
