image_width: 320
image_height: 240
camera_name: narrow_stereo/right
camera_matrix:
  rows: 3
  cols: 3
  data: [250.08891,   0.     , 162.44006,
           0.     , 249.9751 , 118.63512,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.101765, -0.119418, -0.005056, 0.007459, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.99895446, -0.01749419,  0.04223666,
          0.01844369,  0.99958349, -0.02219638,
         -0.04183076,  0.02295218,  0.99886104]
projection_matrix:
  rows: 3
  cols: 4
  data: [275.41799,   0.     , 150.76301, -22.56334,
           0.     , 275.41799, 119.36878,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
