image_width: 320
image_height: 240
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [289.83631,   0.     , 150.21104,
           0.     , 290.76662, 127.9637 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.096071, -0.205751, 0.010930, -0.011322, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [291.91644,   0.     , 146.24453,   0.     ,
           0.     , 294.59323, 129.55488,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
