image_width: 320
image_height: 240
camera_name: narrow_stereo/right
camera_matrix:
  rows: 3
  cols: 3
  data: [251.54227,   0.     , 159.4925 ,
           0.     , 252.11631, 123.85256,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.416871, 0.167023, -0.000294, 0.000398, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 0.99927489,  0.00151528, -0.03804463,
         -0.00172488,  0.99998351, -0.00547694,
          0.0380357 ,  0.00553859,  0.99926103]
projection_matrix:
  rows: 3
  cols: 4
  data: [233.17798,   0.     , 180.60299, -14.81413,
           0.     , 233.17798, 130.65003,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
